apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAlASYYp0TJnSQVSO8GfAAOYAfNX8wvHAdaUIPwQV8ovJm6yKk+MmCLaQPiIg38OQu+mdhViF1FGAXTlON3aiUwx+1ZMEQ4TG2JKFI/HuFdu2/Js9M22caqSo2E5TKelbGLbuAgktHV+U54Q9BJO0LTxMa9pe9VCVvTgZcTmVbJj3LvTvfDFVRPMK2gd4nhhpRytJsW+5vSS2GG6eq7k1H4Btsvhp5BWrW4lqCpsxOwg6qHvVfznYRY811QlcEVzYwn2d4HWB/2WNM4qMlZSXUWIUcHPOfDdTPg/cUGtnPXOOHuTJST2/iKlysrtifRNESgQ8RZ6IdDL+LRb0cqhRgTWj94w3VgJl6vWjw2NOi0Z4MhO+n/nHD9Gq6CSG83bqcNnzFJPXlTjIDg6xdKXHkyP8K+7aI7E8YjYkwXEAL0X9JVKyXPdHoSGN4uA0oA539OrA4uLW3eYLPb01jJRNDVSnEytjzGFa3/5qD2Nlt5bmR2V81VM9MH5s1oaPZDObm6iWewuDAfOhLsTxymlGWHWfNGskBxRQ54ZLEaeDsLU/JdCiZ8zr2fSIipYFTj94qLYf2/80UsdqQ3ZpdznnKHhzu1QwM5li38m9pVDGqheddBKWFiFx5ffqvo8bgHeam0dYpOjKrEiuxS9PxPVFW4MPYgDOdnNQIIBs5UzTc/cs+Fbobm3P03xQqiUlv4sDeaQ2HB+qlupA==
    DB_USER: AgCVDh3Jv8xKTCb17SEnQKsBnpFt4MU2MLAHHo+WHiGKlBaUBozauPs1gFum2kYONsuLqEbGj38n5HUIHbeB6MaAyojyrxB6L/xILYGi02mI1TRxNc24vw2zh4ZlMDskuQcWxOMvTPWQ2Q7Y+UPcS7lfPEc5khOk0h5kixToiUT09Cp8uqTt1XSMZVox6J+jMAYbJjfa/xXu7iI4BpsTxIsKAg/p1fiwEHE9ZJNm+7JYj9V82Nr/A3HnPGxRcZbA7MYoWrFRejj9aWDUf+23DOPxfHodPIsiGpVSjNuFA9+pP52BV4+2h6fD6qwfoDfhwAOCk+l7BAVrxnweTk6N2IepESMdMhOv4de4YJuHIU407xUg0gUKpEzYBA6nfUOPYswm3i5dMWrNRFUb8PIvDTK0k3PRu/G9WgFvpG2I6lu1Tcdd0ZOqoiVY4JRSY1OW9tiEQXuffYcR/PkHGqSCtZdgrp8tacZ7yhOeFKRlFbf+VeIFeCY+0Mlzvy7SE8UJjpNBOs9x6J0cJIDaLphQV2uE+vsB0ofkRLjybmOQyfiCOyWrlxU+v8QnQy2YSdAKxfLb2vaS+cIexnNhqvaFcH405lSfEKVqp71nhufmcuikARJq+G9uYIbE+pzEF6baH34XYNBTkNJ8SoaYTwSgUFi1zK+ADBLm/Rd8Gm7Y2bHGSOMDwnGYYAIjFEPmabnbWxlywT+JOeO2KQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

